### ISSUE TITLE
Get "Cannot create property '_updatedFibers' on number '0'" when using React 18

### ISSUE THREAD

**Issue by robcalcroft** [single-spa/single-spa-react#175]
I get a fatal error when upgrading my apps to React 18 and using single spa react 5 with React 18 support. Any idea whats happening here? I've tried also just rendering a simple app of `<div>Hello</div>` and I get the same issue so I don't think its to do my app setup. I tried with another app and it does the same thing.
React: 18.2 (development)
ReactDOM: 18.2 (development)
single-spa-react: 5.0.0 (not using 5.1.0 as it looks like its broken atm)
Error:
```
Uncaught TypeError: application '@apps/my-app' died in status SKIP_BECAUSE_BROKEN: Cannot create property '_updatedFibers' on number '0'
    at vy (react-dom.development.js:25427:22)
    at Qb (react-dom.development.js:28825:16)
    at ww.render.bw.render (react-dom.development.js:29324:5)
    at i.elementToRender (single-spa-react.js:1:5030)
    at single-spa-react.js:1:5125
    at new Promise (<anonymous>)
    at s (single-spa-react.js:1:3895)
    at lifecycle.helpers.js:28:29
```
Lifecycle setup:
```javascript
const lifecycles = singleSpaReact({
  React,
  ReactDOMClient,
  rootComponent: App,
  errorBoundary(err: Error) {
    return <div>There was an error {err.message}</div>;
  }
});
```

**Comment by gjhommersom** [comment]
Any update on this issue? I'm currently also in the process of upgrading to React 18 and have run into the same issue. 

React: 18.2.0
ReactDom: 18.2.0
SingleSpaReact: 5.2.0

**Comment by gjhommersom** [comment]
I've investigated this a bit more and it seems to be caused by depending on both React17 and React18 in the same microfrontend. This can happen when you have an external that also depends on react but uses a different version.

Something like this:
- Microfrontend 1
  - React18
  - Microfrontend 2
    - React17

**Comment by MilanKovacic** [comment]
Did you solve the issue?

**Comment by MilanKovacic** [comment]
Closing due to inactivity. Feel free to reopen the issue if the problem still occurs.

**Comment by Tiberriver256** [comment]
If the solution provided by @gjhommersom doesn't work out and you actually do need to run React 17 **and** React 18 side by side. You'll want to re-bundle `react-dom` as a utility module with the externals re-pointing `react` to the correct version you want to use.

I wrote up a [detailed walkthrough](https://tiberriver256.github.io/web%20development/how-to-run-multiple-react-versions-using-single-spa/) and made a [repo for reference](https://github.com/Tiberriver256/multiple-react-versions-single-spa).
